name: april_flutter_utils
description: A package for flutter APP development.
version: 0.1.2+1
homepage: "https://github.com/AAAAAApril/flutter_develop_support.git"

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter

  # 地址：https://pub.flutter-io.cn/packages/crypto
  crypto: ^3.0.2

  # 地址：https://pub.flutter-io.cn/packages/flutter_staggered_grid_view
  flutter_staggered_grid_view: ^0.6.2

  # 地址：https://pub.flutter-io.cn/packages/visibility_detector
  visibility_detector: ^0.4.0+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.april.support
        pluginClass: AprilPlugin
