name: april_flutter_utils
description: A package for flutter APP development.
version: 0.1.3
homepage: "https://github.com/AAAAAApril/flutter_develop_support"

environment:
  sdk: ">=2.18.0 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter

  crypto: ^3.0.2
  flutter_staggered_grid_view: ^0.6.2
  visibility_detector: ^0.4.0+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.april.support
        pluginClass: AprilPlugin

# 发布插件执行命令
# flutter packages pub publish --server=https://pub.dartlang.org
